### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by bridgettighe** [bridgettighe/components-on-a-grid#1]
Here is my spoken code for the components on a grid assignment. 

https://user-images.githubusercontent.com/77281280/134379749-f2f5509e-5312-4376-b7bc-6a9a979e2300.mp4

@thatkidmadrid

**Comment by thatkidmadrid** [comment]
Great!
Only small note would be that `rem` is pronounced phonetically as `rehm` no need to say the abbreviation `r-e-m` :)
Other than that, everything looks fine and sounds fine 👍
